### ISSUE TITLE
Longest Path in DAG: extra dataset

### ISSUE THREAD

**Issue by ndtvchris** [BioinformaticsAlgorithms/BioinformaticsAlgorithms.github.io#2]
Hello,

I noticed that when I tried to get the extra dataset for this problem, it showed a 404 file not found. Following the link here, I saw the file was deleted. Could I get the extra dataset please? My students would really appreciate it to test their code.

Warm regards,
Chris

**Comment by phcompeau** [comment]
Thanks for reporting! Should be fixed in a bit.

In the meantime, your students can find an extra dataset at https://bioinformaticsalgorithms.com/data/extradatasets/alignment/LongestPath.txt.
